# Generated by Django 5.2 on 2025-04-17 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_alter_participation_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='away_score_bet',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='bet',
            name='home_score_bet',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pool',
            name='participants',
            field=models.ManyToManyField(related_name='joined_pools', through='pools.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pool',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='status',
            field=models.CharField(choices=[('open', 'Aberto'), ('locked', 'Fechado'), ('finished', 'Encerrado')], default='open', max_length=20),
        ),
    ]
