# Generated by Django 5.2 on 2025-04-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='importar_jogos_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='pontos_acerto_exato',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pool',
            name='pontos_acerto_vencedor',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pool',
            name='pontos_acerto_vencedor_e_diferenca',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pool',
            name='pontos_erro',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('temporada', models.CharField(max_length=10)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='campeonatos/')),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.sport')),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pools.campeonato'),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
                ('gols_casa', models.IntegerField(blank=True, null=True)),
                ('gols_visitante', models.IntegerField(blank=True, null=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='pools.campeonato')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='partida_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pools.partida'),
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='times/')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='pools.campeonato')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='time_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='pools.time'),
        ),
        migrations.AddField(
            model_name='partida',
            name='time_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='pools.time'),
        ),
    ]
