# Generated by Django 5.2 on 2025-04-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0006_alter_campeonato_options_alter_partida_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Esporte', 'verbose_name_plural': 'Esportes'},
        ),
        migrations.RenameField(
            model_name='pool',
            old_name='importar_jogos_automaticamente',
            new_name='import_matches_automatically',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='pontos_acerto_exato',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='pontos_acerto_vencedor',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='pontos_acerto_vencedor_e_diferenca',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='pontos_erro',
        ),
        migrations.AddField(
            model_name='campeonato',
            name='api_endpoint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='api_provider',
            field=models.CharField(blank=True, choices=[('football-data', 'Football-Data.org'), ('api-football', 'API-Football'), ('sportmonks', 'SportMonks'), ('manual', 'Atualização Manual')], max_length=50),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='auto_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='external_api_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='update_frequency',
            field=models.IntegerField(default=24, help_text='Frequência de atualização em horas'),
        ),
        migrations.AddField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='pools.pool'),
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='external_api_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partida',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='local',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partida',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('ao_vivo', 'Ao vivo'), ('encerrada', 'Encerrada'), ('adiada', 'Adiada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
        migrations.AddField(
            model_name='pool',
            name='correct_difference_points',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pool',
            name='correct_winner_points',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pool',
            name='exact_score_points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pool',
            name='wrong_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time',
            name='cor_primaria',
            field=models.CharField(default='#000000', help_text='Cor principal do time (código HEX)', max_length=7),
        ),
        migrations.AddField(
            model_name='time',
            name='external_api_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='time',
            name='nome_curto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pool',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor para participar do bolão', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pool',
            name='max_participants',
            field=models.IntegerField(default=0, help_text='0 para ilimitado'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='status',
            field=models.CharField(choices=[('open', 'Aberto'), ('locked', 'Fechado'), ('finished', 'Encerrado')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='pool',
            name='visibility',
            field=models.CharField(choices=[('public', 'Público'), ('private', 'Privado')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='sport',
            name='icon',
            field=models.CharField(blank=True, help_text='Classes de ícone Font Awesome', max_length=50),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('jogos', models.PositiveIntegerField(default=0)),
                ('vitorias', models.PositiveIntegerField(default=0)),
                ('empates', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('gols_pro', models.PositiveIntegerField(default=0)),
                ('gols_contra', models.PositiveIntegerField(default=0)),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao', to='pools.campeonato')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao', to='pools.time')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ['posicao'],
            },
        ),
    ]
