# Generated by Django 5.2 on 2025-04-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0007_alter_sport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='campeonato',
        ),
        migrations.RemoveField(
            model_name='classificacao',
            name='campeonato',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='campeonato',
        ),
        migrations.RemoveField(
            model_name='time',
            name='campeonato',
        ),
        migrations.RemoveField(
            model_name='classificacao',
            name='time',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='time_casa',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='time_visitante',
        ),
        migrations.RemoveField(
            model_name='match',
            name='partida_relacionada',
        ),
        migrations.AlterModelOptions(
            name='bet',
            options={'verbose_name': 'Bet', 'verbose_name_plural': 'Bets'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Invitation', 'verbose_name_plural': 'Invitations'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['start_time'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Participation', 'verbose_name_plural': 'Participations'},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pool', 'verbose_name_plural': 'Pools'},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='participation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pool',
            name='betting_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for placing bets', null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee to join the pool', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pool',
            name='max_participants',
            field=models.IntegerField(default=0, help_text='0 for unlimited'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('finished', 'Finished')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='pool',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='championships/')),
                ('description', models.TextField(blank=True)),
                ('api_provider', models.CharField(blank=True, choices=[('football-data', 'Football-Data.org'), ('api-football', 'API-Football'), ('sportmonks', 'SportMonks'), ('manual', 'Manual Update')], max_length=50)),
                ('external_api_id', models.CharField(blank=True, max_length=100)),
                ('api_endpoint', models.CharField(blank=True, max_length=255)),
                ('auto_update', models.BooleanField(default=False)),
                ('update_frequency', models.IntegerField(default=24, help_text='Update frequency in hours')),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.sport')),
            ],
            options={
                'verbose_name': 'Championship',
                'verbose_name_plural': 'Championships',
            },
        ),
        migrations.AddField(
            model_name='pool',
            name='championship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='pools.championship'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('finished', models.BooleanField(default=False)),
                ('external_api_id', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='pools.championship')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='related_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_matches', to='pools.game'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('primary_color', models.CharField(default='#000000', help_text="Team's main color (HEX code)", max_length=7)),
                ('external_api_id', models.CharField(blank=True, max_length=100)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='pools.championship')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('played', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('drawn', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='pools.championship')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='pools.team')),
            ],
            options={
                'verbose_name': 'Standing',
                'verbose_name_plural': 'Standings',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='pools.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='pools.team'),
        ),
        migrations.DeleteModel(
            name='Campeonato',
        ),
        migrations.DeleteModel(
            name='Classificacao',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.DeleteModel(
            name='Partida',
        ),
    ]
