# Generated by Django 5.2 on 2025-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0010_make_team_fks_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(max_length=100),
        ),
    ]
