version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bolao_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bolao_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: bolao_web
    command: >
      sh -c "python manage.py migrate --settings=bolao_config.settings_production &&
             python manage.py collectstatic --noinput --settings=bolao_config.settings_production &&
             gunicorn bolao_config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Celery Worker (opcional - para tasks assíncronas)
  celery:
    build: .
    container_name: bolao_celery
    command: celery -A bolao_config worker -l info
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
      - redis
    # Descomente para ativar
    # profiles:
    #   - celery

  # Celery Beat (opcional - para tarefas agendadas)
  celery-beat:
    build: .
    container_name: bolao_celery_beat
    command: celery -A bolao_config beat -l info
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
      - redis
    # Descomente para ativar
    # profiles:
    #   - celery

volumes:
  mysql_data:
  redis_data:
